apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ChinhVNguyen/techtrends-project1.git'  # Replace with the URL of your Helm chart repository
    targetRevision: HEAD
    path: techtrends
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true